//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Sqlite : global::System.Configuration.ApplicationSettingsBase {
        
        private static Sqlite defaultInstance = ((Sqlite)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Sqlite())));
        
        public static Sqlite Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".")]
        public string PathToDatabaseFile {
            get {
                return ((string)(this["PathToDatabaseFile"]));
            }
            set {
                this["PathToDatabaseFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_test.db")]
        public string DatabaseFileName {
            get {
                return ((string)(this["DatabaseFileName"]));
            }
            set {
                this["DatabaseFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CreateDatabaseScript {
            get {
                return ((string)(this["CreateDatabaseScript"]));
            }
            set {
                this["CreateDatabaseScript"] = value;
            }
        }
    }
}
