//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class TestSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static TestSettings defaultInstance = ((TestSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TestSettings())));
        
        public static TestSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local); Initial Catalog={0}; Integrated Security=true; Connection Ti" +
            "meout=10; Max Pool Size=50;")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
            set {
                this["ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("__resequel_TestScopeDatabase_FeelFreeToDeleteIt")]
        public string DatabaseName {
            get {
                return ((string)(this["DatabaseName"]));
            }
            set {
                this["DatabaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USE [master]\r\nGO\r\n\r\nDROP DATABASE IF EXISTS [{0}]\r\nGO\r\n\r\n/****** Object:  Databas" +
            "e [{0}]    ******/\r\nCREATE DATABASE [{0}]\r\n CONTAINMENT = NONE\r\n\r\nALTER DATABASE" +
            " [{0}] SET COMPATIBILITY_LEVEL = 140\r\nGO\r\n\r\n--IF (1 = FULLTEXTSERVICEPROPERTY(\'I" +
            "sFullTextInstalled\'))\r\n--begin\r\n--EXEC [{0}].[dbo].[sp_fulltext_database] @actio" +
            "n = \'enable\'\r\n--end\r\n--GO\r\n\r\nALTER DATABASE [{0}] SET ANSI_NULL_DEFAULT OFF \r\nGO" +
            "\r\n\r\nALTER DATABASE [{0}] SET ANSI_NULLS OFF \r\nGO\r\n\r\nALTER DATABASE [{0}] SET ANS" +
            "I_PADDING OFF \r\nGO\r\n\r\nALTER DATABASE [{0}] SET ANSI_WARNINGS OFF \r\nGO\r\n\r\nALTER D" +
            "ATABASE [{0}] SET ARITHABORT OFF \r\nGO\r\n\r\nALTER DATABASE [{0}] SET AUTO_CLOSE OFF" +
            " \r\nGO\r\n\r\nALTER DATABASE [{0}] SET AUTO_SHRINK OFF \r\nGO\r\n\r\nALTER DATABASE [{0}] S" +
            "ET AUTO_UPDATE_STATISTICS ON \r\nGO\r\n\r\nALTER DATABASE [{0}] SET CURSOR_CLOSE_ON_CO" +
            "MMIT OFF \r\nGO\r\n\r\nALTER DATABASE [{0}] SET CURSOR_DEFAULT  GLOBAL \r\nGO\r\n\r\nALTER D" +
            "ATABASE [{0}] SET CONCAT_NULL_YIELDS_NULL OFF \r\nGO\r\n\r\nALTER DATABASE [{0}] SET N" +
            "UMERIC_ROUNDABORT OFF \r\nGO\r\n\r\nALTER DATABASE [{0}] SET QUOTED_IDENTIFIER OFF \r\nG" +
            "O\r\n\r\nALTER DATABASE [{0}] SET RECURSIVE_TRIGGERS OFF \r\nGO\r\n\r\nALTER DATABASE [{0}" +
            "] SET  DISABLE_BROKER \r\nGO\r\n\r\nALTER DATABASE [{0}] SET AUTO_UPDATE_STATISTICS_AS" +
            "YNC OFF \r\nGO\r\n\r\nALTER DATABASE [{0}] SET DATE_CORRELATION_OPTIMIZATION OFF \r\nGO\r" +
            "\n\r\nALTER DATABASE [{0}] SET TRUSTWORTHY OFF \r\nGO\r\n\r\nALTER DATABASE [{0}] SET ALL" +
            "OW_SNAPSHOT_ISOLATION OFF \r\nGO\r\n\r\nALTER DATABASE [{0}] SET PARAMETERIZATION SIMP" +
            "LE \r\nGO\r\n\r\nALTER DATABASE [{0}] SET READ_COMMITTED_SNAPSHOT OFF \r\nGO\r\n\r\nALTER DA" +
            "TABASE [{0}] SET HONOR_BROKER_PRIORITY OFF \r\nGO\r\n\r\nALTER DATABASE [{0}] SET RECO" +
            "VERY FULL \r\nGO\r\n\r\nALTER DATABASE [{0}] SET  MULTI_USER \r\nGO\r\n\r\nALTER DATABASE [{" +
            "0}] SET PAGE_VERIFY CHECKSUM  \r\nGO\r\n\r\nALTER DATABASE [{0}] SET DB_CHAINING OFF \r" +
            "\nGO\r\n\r\nALTER DATABASE [{0}] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) \r\nGO\r\n" +
            "\r\nALTER DATABASE [{0}] SET TARGET_RECOVERY_TIME = 60 SECONDS \r\nGO\r\n\r\nALTER DATAB" +
            "ASE [{0}] SET DELAYED_DURABILITY = DISABLED \r\nGO\r\n\r\nALTER DATABASE [{0}] SET QUE" +
            "RY_STORE = OFF\r\nGO\r\n\r\nALTER DATABASE [{0}] SET  READ_WRITE \r\nGO\r\n\r\n\r\nUSE [{0}]\r\n" +
            "GO\r\n/****** Object:  Table [dbo].[TestTable0]   ******/\r\nSET ANSI_NULLS ON\r\nGO\r\n" +
            "SET QUOTED_IDENTIFIER ON\r\nGO\r\nCREATE TABLE [dbo].[TestTable0](\r\n\t[id] [int] NOT " +
            "NULL,\r\n\t[name] [varchar](100) NOT NULL,\r\n\t[additional] [varchar](100) NULL,\r\n CO" +
            "NSTRAINT [PK_TestTable0] PRIMARY KEY CLUSTERED \r\n(\r\n\t[id] ASC\r\n)WITH (PAD_INDEX " +
            "= OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON," +
            " ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]\r\n) ON [PRIMARY]\r\nGO\r\n\r\nINSERT [dbo].[TestTa" +
            "ble0] ([id], [name]) VALUES (1, N\'Record 1\')\r\nGO\r\nINSERT [dbo].[TestTable0] ([id" +
            "], [name]) VALUES (2, N\'Record 2\')\r\nGO\r\nINSERT [dbo].[TestTable0] ([id], [name])" +
            " VALUES (3, N\'Record 3\')\r\nGO\r\n\r\n\r\nCREATE NONCLUSTERED INDEX [TestTable0_Index0] " +
            "ON [dbo].[TestTable0]\r\n(\r\n\t[name] ASC\r\n)\r\nINCLUDE ( [additional]) WITH (PAD_INDE" +
            "X = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF" +
            ", ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]\r\nGO\r\n\r" +
            "\n\r\n\r\n\r\nCREATE TABLE [dbo].[TestTable1](\r\n\t[id] [int] NOT NULL,\r\n\t[name] [varchar" +
            "](100) NOT NULL,\r\n\t[additional] [varchar](100) NULL,\r\n CONSTRAINT [PK_TestTable1" +
            "] PRIMARY KEY CLUSTERED \r\n(\r\n\t[id] ASC\r\n)WITH (PAD_INDEX = OFF, STATISTICS_NOREC" +
            "OMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)" +
            " ON [PRIMARY]\r\n) ON [PRIMARY]\r\nGO\r\n\r\nCREATE TABLE [dbo].[TestTable2](\r\n\t[id] [in" +
            "t] NOT NULL,\r\n\t[name] [varchar](100) NOT NULL,\r\n\t[additional] [varchar](100) NUL" +
            "L,\r\n CONSTRAINT [PK_TestTable2] PRIMARY KEY CLUSTERED \r\n(\r\n\t[id] ASC\r\n)WITH (PAD" +
            "_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCK" +
            "S = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]\r\n) ON [PRIMARY]\r\nGO\r\n\r\nuse [master]\r" +
            "\nGO")]
        public string CreateDatabaseScript {
            get {
                return ((string)(this["CreateDatabaseScript"]));
            }
            set {
                this["CreateDatabaseScript"] = value;
            }
        }
    }
}
